apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-deployment
  labels:
    purpose: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ritika0812/task1:v1
        ports:
        -  containerPort: 8081 
