apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    purpose: service
spec:
  selector:
    app: nginx
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30861
  type: NodePort
