name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ritika0812/task1:latest
          
      - name: deploying in k8
        run: |
          minikube start
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          sleep 25
          kubectl get deployments
          minikube service nginx-service --url
          kubectl get pods
          
